## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
title = "Ariel's Doodles"
copyright = "2026"
theme = "hugo-story"


## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  enableShop = true
  cartWorkerURL = "https://arielsdoodles-cart.fchujon.workers.dev"
  stripePublishableKey = "pk_test_51NYiz2GWnDaMybgFD1k2fJbIF0VCuqn7VZoaVRCmbHEqnwgW0ZtFvpxNecZLJhhDnkQkYQ4erWZGd589Df7jx3Cw00oANyO28m"

[Params.social]
  email = "arielchujonart@gmail.com"
  facebook = "https://www.facebook.com/arielchujonart"
  instagram = "https://www.instagram.com/ariel_chujon_art"
  reddit = "https://www.reddit.com/u/arielsdoodles"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  arielsdoodles_cs = ["css/arielsdoodles.css"]

