[context.production.environment]
HUGO_VERSION="0.110.0"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.images]
  compress = true